server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: material_management
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.10.10:3306/material?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  #Redis的相关配置
  redis:
    host: 127.0.0.1
    port: 6379
 #   password: 123456
    database: 0 #默认使用0号数据库
    jedis:
      #redis的连接配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 5ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中最大空闲连接
        min-idle: 0 #连接池中最小空闲连接
mybatis-plus:
  #注册实体类
  type-aliases-package: com.rblue.dto
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    扫描包配置文件
    mapper-locations: classpath:mapper/*.xml

  global-config:
    db-config:
      id-type: ASSIGN_ID



